
### Imported Libraries

> NumPy : Library for Numeric Computations in Python  
> Pandas : Library for Data Acquisition and Preparation  
> Matplotlib : Low-level library for Data Visualization  
> Seaborn : Higher-level library for Data Visualization

In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
sb.set()

### Import the Dataset

In [2]:
aviationdata = pd.read_csv('AviationDataUP.csv')
aviationdata.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.Flight,Air.Carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.Phase.of.Flight,Report.Status,Publication.Date
0,20161117X64217,Accident,WPR17WA022,14/11/2016,"Winton, New Zealand",New Zealand,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,MANEUVERING,Foreign,NaN
1,20161116X13203,Accident,CEN17WA040,14/11/2016,"Albrook, Panama",Panama,NaN,NaN,MPMG,Marcos A. Gelabert Intl.,...,NaN,NaN,NaN,NaN,NaN,2.0,VMC,LANDING,Foreign,NaN
2,20161116X62135,Accident,CEN17LA041,13/11/2016,"Port Allen, LA",United States,30.532500,-91.3150,LA46,OMNI,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,TAKEOFF,Preliminary,22/11/2016
3,20161114X41943,Accident,WPR17LA020,12/11/2016,"Taylor, AZ",United States,34.454722,-110.0575,NaN,NaN,...,Instructional,NaN,NaN,NaN,NaN,2.0,VMC,MANEUVERING,Preliminary,22/11/2016
4,20161116X04207,Accident,CEN17LA039,12/11/2016,"Pleasanton, TX",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,NaN,1.0,NaN,1.0,VMC,NaN,Preliminary,16/11/2016